# .goreleaser.yml
# Build customization
builds:
  - main: s5cmd.go
    binary: s5cmd
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
# Archive customization
archive:
  format: tar.gz
